name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm test

      - if: github.ref == 'refs/heads/master'
        run: pnpm build

      - if: github.ref == 'refs/heads/master'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build
